/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPortalVendedorRouteImport } from './routes/_authenticated/portal-vendedor'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBuscaLeadsRouteImport } from './routes/_authenticated/busca-leads'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as ApiPublicZapiWebhookRouteImport } from './routes/api/public/zapi-webhook'
import { Route as ApiPublicResendWebhookRouteImport } from './routes/api/public/resend-webhook'
import { Route as ApiPublicProspectingTickRouteImport } from './routes/api/public/prospecting-tick'
import { Route as ApiPublicOutreachTickRouteImport } from './routes/api/public/outreach-tick'
import { Route as ApiPublicLeadFlowTickRouteImport } from './routes/api/public/lead-flow-tick'
import { Route as ApiPublicEvolutionWebhookRouteImport } from './routes/api/public/evolution-webhook'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalVendedorRoute =
  AuthenticatedPortalVendedorRouteImport.update({
    id: '/portal-vendedor',
    path: '/portal-vendedor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuscaLeadsRoute = AuthenticatedBuscaLeadsRouteImport.update({
  id: '/busca-leads',
  path: '/busca-leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZapiWebhookRoute = ApiPublicZapiWebhookRouteImport.update({
  id: '/api/public/zapi-webhook',
  path: '/api/public/zapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResendWebhookRoute = ApiPublicResendWebhookRouteImport.update({
  id: '/api/public/resend-webhook',
  path: '/api/public/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProspectingTickRoute =
  ApiPublicProspectingTickRouteImport.update({
    id: '/api/public/prospecting-tick',
    path: '/api/public/prospecting-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOutreachTickRoute = ApiPublicOutreachTickRouteImport.update({
  id: '/api/public/outreach-tick',
  path: '/api/public/outreach-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadFlowTickRoute = ApiPublicLeadFlowTickRouteImport.update({
  id: '/api/public/lead-flow-tick',
  path: '/api/public/lead-flow-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionWebhookRoute =
  ApiPublicEvolutionWebhookRouteImport.update({
    id: '/api/public/evolution-webhook',
    path: '/api/public/evolution-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/busca-leads': typeof AuthenticatedBuscaLeadsRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/portal-vendedor': typeof AuthenticatedPortalVendedorRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/lead-flow-tick': typeof ApiPublicLeadFlowTickRoute
  '/api/public/outreach-tick': typeof ApiPublicOutreachTickRoute
  '/api/public/prospecting-tick': typeof ApiPublicProspectingTickRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/zapi-webhook': typeof ApiPublicZapiWebhookRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/busca-leads': typeof AuthenticatedBuscaLeadsRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/portal-vendedor': typeof AuthenticatedPortalVendedorRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/': typeof AuthenticatedIndexRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/lead-flow-tick': typeof ApiPublicLeadFlowTickRoute
  '/api/public/outreach-tick': typeof ApiPublicOutreachTickRoute
  '/api/public/prospecting-tick': typeof ApiPublicProspectingTickRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/zapi-webhook': typeof ApiPublicZapiWebhookRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/busca-leads': typeof AuthenticatedBuscaLeadsRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/portal-vendedor': typeof AuthenticatedPortalVendedorRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/lead-flow-tick': typeof ApiPublicLeadFlowTickRoute
  '/api/public/outreach-tick': typeof ApiPublicOutreachTickRoute
  '/api/public/prospecting-tick': typeof ApiPublicProspectingTickRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/zapi-webhook': typeof ApiPublicZapiWebhookRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/atendimento'
    | '/busca-leads'
    | '/configuracoes'
    | '/diagnostico'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/relatorios'
    | '/leads/$id'
    | '/api/public/evolution-webhook'
    | '/api/public/lead-flow-tick'
    | '/api/public/outreach-tick'
    | '/api/public/prospecting-tick'
    | '/api/public/resend-webhook'
    | '/api/public/zapi-webhook'
    | '/oauth/google-calendar/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/atendimento'
    | '/busca-leads'
    | '/configuracoes'
    | '/diagnostico'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/relatorios'
    | '/'
    | '/leads/$id'
    | '/api/public/evolution-webhook'
    | '/api/public/lead-flow-tick'
    | '/api/public/outreach-tick'
    | '/api/public/prospecting-tick'
    | '/api/public/resend-webhook'
    | '/api/public/zapi-webhook'
    | '/oauth/google-calendar/return'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/atendimento'
    | '/_authenticated/busca-leads'
    | '/_authenticated/configuracoes'
    | '/_authenticated/diagnostico'
    | '/_authenticated/empresa'
    | '/_authenticated/leads'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pedidos'
    | '/_authenticated/portal-vendedor'
    | '/_authenticated/relatorios'
    | '/_authenticated/'
    | '/_authenticated/leads/$id'
    | '/api/public/evolution-webhook'
    | '/api/public/lead-flow-tick'
    | '/api/public/outreach-tick'
    | '/api/public/prospecting-tick'
    | '/api/public/resend-webhook'
    | '/api/public/zapi-webhook'
    | '/oauth/google-calendar/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicEvolutionWebhookRoute: typeof ApiPublicEvolutionWebhookRoute
  ApiPublicLeadFlowTickRoute: typeof ApiPublicLeadFlowTickRoute
  ApiPublicOutreachTickRoute: typeof ApiPublicOutreachTickRoute
  ApiPublicProspectingTickRoute: typeof ApiPublicProspectingTickRoute
  ApiPublicResendWebhookRoute: typeof ApiPublicResendWebhookRoute
  ApiPublicZapiWebhookRoute: typeof ApiPublicZapiWebhookRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-vendedor': {
      id: '/_authenticated/portal-vendedor'
      path: '/portal-vendedor'
      fullPath: '/portal-vendedor'
      preLoaderRoute: typeof AuthenticatedPortalVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/busca-leads': {
      id: '/_authenticated/busca-leads'
      path: '/busca-leads'
      fullPath: '/busca-leads'
      preLoaderRoute: typeof AuthenticatedBuscaLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapi-webhook': {
      id: '/api/public/zapi-webhook'
      path: '/api/public/zapi-webhook'
      fullPath: '/api/public/zapi-webhook'
      preLoaderRoute: typeof ApiPublicZapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-webhook': {
      id: '/api/public/resend-webhook'
      path: '/api/public/resend-webhook'
      fullPath: '/api/public/resend-webhook'
      preLoaderRoute: typeof ApiPublicResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prospecting-tick': {
      id: '/api/public/prospecting-tick'
      path: '/api/public/prospecting-tick'
      fullPath: '/api/public/prospecting-tick'
      preLoaderRoute: typeof ApiPublicProspectingTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outreach-tick': {
      id: '/api/public/outreach-tick'
      path: '/api/public/outreach-tick'
      fullPath: '/api/public/outreach-tick'
      preLoaderRoute: typeof ApiPublicOutreachTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-flow-tick': {
      id: '/api/public/lead-flow-tick'
      path: '/api/public/lead-flow-tick'
      fullPath: '/api/public/lead-flow-tick'
      preLoaderRoute: typeof ApiPublicLeadFlowTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution-webhook': {
      id: '/api/public/evolution-webhook'
      path: '/api/public/evolution-webhook'
      fullPath: '/api/public/evolution-webhook'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
  }
}

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedBuscaLeadsRoute: typeof AuthenticatedBuscaLeadsRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPortalVendedorRoute: typeof AuthenticatedPortalVendedorRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedBuscaLeadsRoute: AuthenticatedBuscaLeadsRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPortalVendedorRoute: AuthenticatedPortalVendedorRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicEvolutionWebhookRoute: ApiPublicEvolutionWebhookRoute,
  ApiPublicLeadFlowTickRoute: ApiPublicLeadFlowTickRoute,
  ApiPublicOutreachTickRoute: ApiPublicOutreachTickRoute,
  ApiPublicProspectingTickRoute: ApiPublicProspectingTickRoute,
  ApiPublicResendWebhookRoute: ApiPublicResendWebhookRoute,
  ApiPublicZapiWebhookRoute: ApiPublicZapiWebhookRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
