/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScoringRouteImport } from './routes/_authenticated.scoring'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedProspeccaoRouteImport } from './routes/_authenticated.prospeccao'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedPlaybooksRouteImport } from './routes/_authenticated.playbooks'
import { Route as AuthenticatedPerfisBuscaRouteImport } from './routes/_authenticated.perfis-busca'
import { Route as AuthenticatedListasRouteImport } from './routes/_authenticated.listas'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated.leads'
import { Route as AuthenticatedHandoffsRouteImport } from './routes/_authenticated.handoffs'
import { Route as AuthenticatedEstrategiaRouteImport } from './routes/_authenticated.estrategia'
import { Route as AuthenticatedEmpresaServicosRouteImport } from './routes/_authenticated.empresa-servicos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedCentralRouteImport } from './routes/_authenticated.central'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated.campanhas'
import { Route as AuthenticatedCadenciasRouteImport } from './routes/_authenticated.cadencias'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated.atendimentos'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated.leads.$leadId'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScoringRoute = AuthenticatedScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspeccaoRoute = AuthenticatedProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaybooksRoute = AuthenticatedPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfisBuscaRoute =
  AuthenticatedPerfisBuscaRouteImport.update({
    id: '/perfis-busca',
    path: '/perfis-busca',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListasRoute = AuthenticatedListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHandoffsRoute = AuthenticatedHandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstrategiaRoute = AuthenticatedEstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresaServicosRoute =
  AuthenticatedEmpresaServicosRouteImport.update({
    id: '/empresa-servicos',
    path: '/empresa-servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCentralRoute = AuthenticatedCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadenciasRoute = AuthenticatedCadenciasRouteImport.update({
  id: '/cadencias',
  path: '/cadencias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/cadencias': typeof AuthenticatedCadenciasRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/central': typeof AuthenticatedCentralRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa-servicos': typeof AuthenticatedEmpresaServicosRoute
  '/estrategia': typeof AuthenticatedEstrategiaRoute
  '/handoffs': typeof AuthenticatedHandoffsRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/listas': typeof AuthenticatedListasRoute
  '/perfis-busca': typeof AuthenticatedPerfisBuscaRoute
  '/playbooks': typeof AuthenticatedPlaybooksRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scoring': typeof AuthenticatedScoringRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/cadencias': typeof AuthenticatedCadenciasRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/central': typeof AuthenticatedCentralRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa-servicos': typeof AuthenticatedEmpresaServicosRoute
  '/estrategia': typeof AuthenticatedEstrategiaRoute
  '/handoffs': typeof AuthenticatedHandoffsRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/listas': typeof AuthenticatedListasRoute
  '/perfis-busca': typeof AuthenticatedPerfisBuscaRoute
  '/playbooks': typeof AuthenticatedPlaybooksRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scoring': typeof AuthenticatedScoringRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/cadencias': typeof AuthenticatedCadenciasRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/central': typeof AuthenticatedCentralRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresa-servicos': typeof AuthenticatedEmpresaServicosRoute
  '/_authenticated/estrategia': typeof AuthenticatedEstrategiaRoute
  '/_authenticated/handoffs': typeof AuthenticatedHandoffsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/listas': typeof AuthenticatedListasRoute
  '/_authenticated/perfis-busca': typeof AuthenticatedPerfisBuscaRoute
  '/_authenticated/playbooks': typeof AuthenticatedPlaybooksRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/scoring': typeof AuthenticatedScoringRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/atendimentos'
    | '/cadencias'
    | '/campanhas'
    | '/central'
    | '/configuracoes'
    | '/dashboard'
    | '/empresa-servicos'
    | '/estrategia'
    | '/handoffs'
    | '/leads'
    | '/listas'
    | '/perfis-busca'
    | '/playbooks'
    | '/portal'
    | '/prospeccao'
    | '/relatorios'
    | '/scoring'
    | '/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/atendimentos'
    | '/cadencias'
    | '/campanhas'
    | '/central'
    | '/configuracoes'
    | '/dashboard'
    | '/empresa-servicos'
    | '/estrategia'
    | '/handoffs'
    | '/leads'
    | '/listas'
    | '/perfis-busca'
    | '/playbooks'
    | '/portal'
    | '/prospeccao'
    | '/relatorios'
    | '/scoring'
    | '/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/recuperar-senha'
    | '/_authenticated/atendimentos'
    | '/_authenticated/cadencias'
    | '/_authenticated/campanhas'
    | '/_authenticated/central'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresa-servicos'
    | '/_authenticated/estrategia'
    | '/_authenticated/handoffs'
    | '/_authenticated/leads'
    | '/_authenticated/listas'
    | '/_authenticated/perfis-busca'
    | '/_authenticated/playbooks'
    | '/_authenticated/portal'
    | '/_authenticated/prospeccao'
    | '/_authenticated/relatorios'
    | '/_authenticated/scoring'
    | '/_authenticated/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scoring': {
      id: '/_authenticated/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof AuthenticatedScoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospeccao': {
      id: '/_authenticated/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof AuthenticatedProspeccaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playbooks': {
      id: '/_authenticated/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof AuthenticatedPlaybooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfis-busca': {
      id: '/_authenticated/perfis-busca'
      path: '/perfis-busca'
      fullPath: '/perfis-busca'
      preLoaderRoute: typeof AuthenticatedPerfisBuscaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listas': {
      id: '/_authenticated/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof AuthenticatedListasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/handoffs': {
      id: '/_authenticated/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof AuthenticatedHandoffsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estrategia': {
      id: '/_authenticated/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof AuthenticatedEstrategiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresa-servicos': {
      id: '/_authenticated/empresa-servicos'
      path: '/empresa-servicos'
      fullPath: '/empresa-servicos'
      preLoaderRoute: typeof AuthenticatedEmpresaServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadencias': {
      id: '/_authenticated/cadencias'
      path: '/cadencias'
      fullPath: '/cadencias'
      preLoaderRoute: typeof AuthenticatedCadenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
  }
}

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedCadenciasRoute: typeof AuthenticatedCadenciasRoute
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedCentralRoute: typeof AuthenticatedCentralRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresaServicosRoute: typeof AuthenticatedEmpresaServicosRoute
  AuthenticatedEstrategiaRoute: typeof AuthenticatedEstrategiaRoute
  AuthenticatedHandoffsRoute: typeof AuthenticatedHandoffsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedListasRoute: typeof AuthenticatedListasRoute
  AuthenticatedPerfisBuscaRoute: typeof AuthenticatedPerfisBuscaRoute
  AuthenticatedPlaybooksRoute: typeof AuthenticatedPlaybooksRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProspeccaoRoute: typeof AuthenticatedProspeccaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedScoringRoute: typeof AuthenticatedScoringRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedCadenciasRoute: AuthenticatedCadenciasRoute,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedCentralRoute: AuthenticatedCentralRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresaServicosRoute: AuthenticatedEmpresaServicosRoute,
  AuthenticatedEstrategiaRoute: AuthenticatedEstrategiaRoute,
  AuthenticatedHandoffsRoute: AuthenticatedHandoffsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedListasRoute: AuthenticatedListasRoute,
  AuthenticatedPerfisBuscaRoute: AuthenticatedPerfisBuscaRoute,
  AuthenticatedPlaybooksRoute: AuthenticatedPlaybooksRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProspeccaoRoute: AuthenticatedProspeccaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedScoringRoute: AuthenticatedScoringRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
