// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://thgzrkppouoevapjquyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZ3pya3Bwb3VvZXZhcGpxdXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0MDI1NzIsImV4cCI6MjEwMTk3ODU3Mn0.NRenek9GGT1Q61Yzt4-DfvKnlI7ojRwUE83sVPWJ6i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
